### ISSUE TITLE
Play alert sound preview when changing volume of alert sound

### ISSUE THREAD

**Issue by nicholasdly** [nicholasdly/pomodoro#17]
At the moment, a user is unable to gauge how loud the alert sound(s) will be until they actually play at the end of a timer. The alarm sound should play every time the alert volume is changed to give the user an idea of how loud the alert will be.

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly Hi, can you assign this task to me i will do it.

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly Sent a PR resolving the issue.
