### ISSUE TITLE
Display timer state as site title

### ISSUE THREAD

**Issue by nicholasdly** [nicholasdly/pomodoro#18]
Unless the pomodoro timer is an active tab/window on a user's display, the user would have no idea how much time they have left in their work/break interval. The timer should update the site title so that the user can easily reference the time even if the user has a different tab opened.

**Comment by Ayu10x** [comment]
I would like to enhance the Pomodoro timer by updating the browser tab's title to display the remaining time. This will allow users to easily track the timer, even if they switch to another tab.

Could you please assign this task to me?

**Comment by alexandroschanas** [comment]
`function pomodoroTimer(hours,minutes,seconds){

    var total_seconds = (hours * 3600 ) + (minutes * 60) + (seconds);

    var timer = setInterval(function(){

    var count_hours = Math.floor(total_seconds / 3600);
    var count_minutes = Math.floor((total_seconds % 3600) / 60);
    var count_seconds = total_seconds % 60;

   var current_time = (count_hours.toString().padStart(2, '0') + ':' + 
   count_minutes.toString().padStart(2, '0') + ':' + 
   count_seconds.toString().padStart(2, '0'));
    
    document.title = current_time;

    total_seconds--;

    if(total_seconds < 0){
        clearInterval(timer);
    }

    },1000)

}

//Setting the duration , is like setting a duration for 20:10 , 20 minutes and 10 seconds
console.log(pomodoroTimer(10,30,40));`

**Comment by alexandroschanas** [comment]
Hello @nicholasdly , i would like this task assigned if you are interested you can respond to this message.

Thanks.

**Comment by nicholasdly** [comment]
Hey @Ayu10x and @alexandroschanas, I won't be assigning issues to specific people as I am just accepting the first (and best) PR that resolves the issue.

If either of you guys would like to tackle this feature, feel free to fork this repo, make a new branch, make your code changes, and then open a PR.
